version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "3001:3000"
    links:
      - mongo
    volumes:
      - .:/app
    env_file:
      - .env

  mongo:
    image: mongo
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
